-- 抽奖人记录表

DROP TABLE ZHAOBAOGUAN.T_CMS_ACTIVITY_PERSON CASCADE CONSTRAINTS;

CREATE TABLE ZHAOBAOGUAN.T_CMS_ACTIVITY_PERSON
	(
	OID         VARCHAR2 (36) DEFAULT SYS_GUID() PRIMARY KEY ,
	PHONE       VARCHAR2 (20),
	COUNT	    INT,
	PRIZE       INT DEFAULT 0,
        PRIZE_DATE  DATE,
        INVITE_CODE VARCHAR2 (50),
	REGISTER_STAT  INT DEFAULT 0 NOT NULL,
	INSERT_TIME DATE DEFAULT SYSDATE NOT NULL,
        IS_AWARD    INT DEFAULT 0 NOT NULL,
        BATCH  INT NOT NULL
	
	)
comment on table ZHAOBAOGUAN.T_CMS_ACTIVITY_PERSON is '抽奖人记录';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY_PERSON.OID IS 'OID';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY_PERSON.PHONE IS '电话号码';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY_PERSON.COUNT IS '抽奖次数';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY_PERSON.PRIZE IS '中奖奖项';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY_PERSON.PRIZE_DATE IS '中奖日期';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY_PERSON.INVITE_CODE IS '邀请码';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY_PERSON.REGISTER_STAT IS '注册状态 0未注册 ，1 已注册';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY_PERSON.INSERT_TIME IS '数据插入日期';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY_PERSON.IS_AWARD IS '奖项是否颁发';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY_PERSON.BATCH IS '批次';


--抽奖活动表
DROP TABLE ZHAOBAOGUAN.T_CMS_ACTIVITY CASCADE CONSTRAINTS;

CREATE TABLE ZHAOBAOGUAN.T_CMS_ACTIVITY
	(
	BATCH  INT  PRIMARY KEY,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	MAX_RATE  NUMBER(22,5) NOT NULL
	)

comment on table ZHAOBAOGUAN.T_CMS_ACTIVITY is '抽奖活动';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY.BATCH IS '活动批次';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY.START_DATE IS '活动开始时间';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY.END_DATE IS '活动截止时间';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY.MAX_RATE IS '最大中奖概率'; 

DROP TABLE ZHAOBAOGUAN.T_CMS_ACTIVITY_AWARD CASCADE CONSTRAINTS;
--奖项表
CREATE TABLE ZHAOBAOGUAN.T_CMS_ACTIVITY_AWARD
	(
	OID VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY,
	DEGREE	INT NOT NULL,
	REMARK  VARCHAR2(100),
	BATCH  INT NOT NULL,
	MAX_COUNT INT NOT NULL,
	LEFT_COUNT INT NOT NULL
	)
comment on table ZHAOBAOGUAN.T_CMS_ACTIVITY_AWARD is '抽奖活动奖项';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY_AWARD.OID IS 'OID';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY_AWARD.DEGREE IS '奖项级别';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY_AWARD.REMARK IS '奖项说明';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY_AWARD.BATCH IS '活动批次';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY_AWARD.MAX_COUNT IS '奖项总数量';
COMMENT ON COLUMN ZHAOBAOGUAN.T_CMS_ACTIVITY_AWARD.LEFT_COUNT IS '奖项剩余数量';

