

INSERT INTO T_CMS_ACTIVITY VALUES (1,'2016-04-05','2016-04-15',0.1);
COMMIT;

INSERT INTO T_CMS_ACTIVITY_AWARD(DEGREE,REMARK,BATCH,MAX_COUNT,LEFT_COUNT) VALUES (1,'一等奖',1,10,10);
INSERT INTO T_CMS_ACTIVITY_AWARD(DEGREE,REMARK,BATCH,MAX_COUNT,LEFT_COUNT) VALUES (2,'二等奖',1,50,50);
INSERT INTO T_CMS_ACTIVITY_AWARD(DEGREE,REMARK,BATCH,MAX_COUNT,LEFT_COUNT) VALUES (3,'三等奖',1,150,150);
COMMIT;

